engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - "**.js"
  - "**.rb"
exclude_paths:
- spec/**/*
- app/assets/javascripts/chosen.jquery.js
- public/**/*
- "**/vendor/**/*"
